version: '3.6'

services:

  flask-db:
    restart: always
    build:
      context: ./database
      network: host
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: front
    ports:
      - "3303:3306"

  flask-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - flask-db
    links:
      - flask-db:mysql
